/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quiz;




import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Div
 */
public class AddQuestions extends javax.swing.JFrame {
private DBConnection db = new DBConnection();
    /**
     * Creates new form ADD_QUESTIONS
     */
    public AddQuestions() {
        initComponents();
         ResultSet s;
      
    
        try{
            
            PreparedStatement pst = db.getConnection().prepareStatement("select count(q_no) from question",ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
            s = pst.executeQuery();
            if(s.first())
            {
                int q_no = s.getInt(1);
               
               
                q_no = q_no+1;
                String str = String.valueOf(q_no);
                NUMBER.setText(str);
                
            }
            else{
                NUMBER.setText("1");
            }
            
        
            }
        
        catch(Exception e)
        {
          JFrame jf = new JFrame();
          jf.setAlwaysOnTop(true);
          JOptionPane.showMessageDialog(jf,e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addnewquestion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CLOSE = new javax.swing.JButton();
        QNO = new javax.swing.JLabel();
        NUMBER = new javax.swing.JLabel();
        qstat = new javax.swing.JLabel();
        optionA = new javax.swing.JLabel();
        optionB = new javax.swing.JLabel();
        optionC = new javax.swing.JLabel();
        optionD = new javax.swing.JLabel();
        crct_choice = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        q_stat = new javax.swing.JTextField();
        choiceA = new javax.swing.JTextField();
        choiceB = new javax.swing.JTextField();
        choiceC = new javax.swing.JTextField();
        choiceD = new javax.swing.JTextField();
        crct_answer = new javax.swing.JTextField();
        quiz_id = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addnewquestion.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        addnewquestion.setText("ADD NEW QUESTION");
        jPanel1.add(addnewquestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 490, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add new question.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 70));

        CLOSE.setBackground(new java.awt.Color(255, 153, 0));
        CLOSE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compressed_1644052934656.jpeg"))); // NOI18N
        CLOSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSEActionPerformed(evt);
            }
        });
        jPanel1.add(CLOSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 40, -1));

        QNO.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        QNO.setText("q_no");
        jPanel1.add(QNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        NUMBER.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NUMBER.setForeground(new java.awt.Color(51, 0, 204));
        NUMBER.setText("00");
        jPanel1.add(NUMBER, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 20, 20));

        qstat.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        qstat.setText("q_statement:");
        jPanel1.add(qstat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        optionA.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        optionA.setText("A");
        jPanel1.add(optionA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        optionB.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        optionB.setText("B");
        jPanel1.add(optionB, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        optionC.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        optionC.setText("C");
        jPanel1.add(optionC, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 10, -1));

        optionD.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        optionD.setText("D");
        jPanel1.add(optionD, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 20, -1));

        crct_choice.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        crct_choice.setText("crct_choice:");
        jPanel1.add(crct_choice, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clear.setText("Clear");
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
        });
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, -1));

        q_stat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        q_stat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q_statActionPerformed(evt);
            }
        });
        jPanel1.add(q_stat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 510, -1));

        choiceA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(choiceA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 360, -1));

        choiceB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(choiceB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 360, -1));

        choiceC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(choiceC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 360, -1));

        choiceD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        choiceD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceDActionPerformed(evt);
            }
        });
        jPanel1.add(choiceD, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 360, -1));

        crct_answer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(crct_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 360, -1));

        quiz_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        quiz_id.setText("quiz_id:");
        jPanel1.add(quiz_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 40, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void q_statActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q_statActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q_statActionPerformed

    private void choiceDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choiceDActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
         ResultSet s;
        String driver="";
        String url="jdbc:mysql://localhost:3306/quiz";
        String username="root";
        String password="mego2028";
        String quiz_id = jTextField1.getText();
        String q_no = NUMBER.getText();
        String q_statement = q_stat.getText();
        String A = choiceA.getText();
        String B = choiceB.getText();
        String C = choiceC.getText();
        String D = choiceD.getText();
        String crct_choice = crct_answer.getText();
        try{
            Connection c=DriverManager.getConnection(url, username, password);
            String sql = ("insert into question values(?,?,?,?,?,?,?,?)");
            PreparedStatement pst = c.prepareStatement(sql); 
            pst.setString(1,quiz_id);
            pst.setString(2, q_no);
             pst.setString(3, q_statement);
              pst.setString(4, A);
               pst.setString(5,B);
                pst.setString(6,C);
                 pst.setString(7,D);
                 pst.setString(8,crct_choice);
                 pst.executeUpdate();
                  JFrame jf = new JFrame();
          jf.setAlwaysOnTop(true);
          JOptionPane.showMessageDialog(jf,"Successfully Added");
          setVisible(false);
          new AddQuestions().setVisible(true);
        } catch (SQLException ex) {
            JFrame jf = new JFrame();
          jf.setAlwaysOnTop(true);
          JOptionPane.showMessageDialog(jf,ex);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        
        quiz_id.setText("");
         q_stat.setText("");
         choiceA.setText("");
         choiceB.setText("");
         choiceC.setText("");
         choiceD.setText("");
         crct_answer.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_clearMouseClicked

    private void CLOSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSEActionPerformed
        // TODO add your handling code here:
        AdminPage.open=0;
        setVisible(false);
    }//GEN-LAST:event_CLOSEActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddQuestions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLOSE;
    private javax.swing.JLabel NUMBER;
    private javax.swing.JLabel QNO;
    private javax.swing.JLabel addnewquestion;
    private javax.swing.JTextField choiceA;
    private javax.swing.JTextField choiceB;
    private javax.swing.JTextField choiceC;
    private javax.swing.JTextField choiceD;
    private javax.swing.JButton clear;
    private javax.swing.JTextField crct_answer;
    private javax.swing.JLabel crct_choice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel optionA;
    private javax.swing.JLabel optionB;
    private javax.swing.JLabel optionC;
    private javax.swing.JLabel optionD;
    private javax.swing.JTextField q_stat;
    private javax.swing.JLabel qstat;
    private javax.swing.JLabel quiz_id;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
