/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quiz;

/**
 *
 * @author Div
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form INDEX
     */
    public Index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        STUDENT_BUTTON = new javax.swing.JButton();
        LECTURER_BUTTON = new javax.swing.JButton();
        Welcome = new javax.swing.JLabel();
        jPanelwelcome = new javax.swing.JPanel();
        WELCOME = new javax.swing.JLabel();
        LECT_BUTTON = new javax.swing.JButton();
        STUD_BUTTON = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        STUDENT_BUTTON.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        STUDENT_BUTTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compressed-949-2022-02-04-23-13-56.png"))); // NOI18N
        STUDENT_BUTTON.setText("LECTURER");

        LECTURER_BUTTON.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LECTURER_BUTTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compressed_1643975340118.jpeg"))); // NOI18N
        LECTURER_BUTTON.setText("STUDENT");
        LECTURER_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LECTURER_BUTTONActionPerformed(evt);
            }
        });

        Welcome.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        Welcome.setText("WELCOME");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LECTURER_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(STUDENT_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Welcome)
                    .addComponent(STUDENT_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LECTURER_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelwelcome.setBackground(new java.awt.Color(204, 255, 51));
        jPanelwelcome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WELCOME.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        WELCOME.setText("WELCOME");
        jPanelwelcome.add(WELCOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 24, 130, -1));

        LECT_BUTTON.setBackground(new java.awt.Color(255, 255, 255));
        LECT_BUTTON.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LECT_BUTTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compressed-949-2022-02-04-23-13-56.png"))); // NOI18N
        LECT_BUTTON.setText("LECTURER");
        LECT_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LECT_BUTTONActionPerformed(evt);
            }
        });
        jPanelwelcome.add(LECT_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 180, 80));

        STUD_BUTTON.setBackground(new java.awt.Color(255, 255, 255));
        STUD_BUTTON.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        STUD_BUTTON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compressed_1643975340118.jpeg"))); // NOI18N
        STUD_BUTTON.setText("STUDENT");
        STUD_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STUD_BUTTONActionPerformed(evt);
            }
        });
        jPanelwelcome.add(STUD_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 180, 80));

        cancel.setBackground(new java.awt.Color(255, 255, 255));
        cancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compressed_1643995180367.jpeg"))); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanelwelcome.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 150, -1));

        getContentPane().add(jPanelwelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LECTURER_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LECTURER_BUTTONActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_LECTURER_BUTTONActionPerformed

    private void STUD_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STUD_BUTTONActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Students sd = new Students();
        sd.setVisible(true);
    }//GEN-LAST:event_STUD_BUTTONActionPerformed

    private void LECT_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LECT_BUTTONActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        Lecturer lt = new Lecturer();
        lt.setVisible(true);
    }//GEN-LAST:event_LECT_BUTTONActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LECTURER_BUTTON;
    private javax.swing.JButton LECT_BUTTON;
    private javax.swing.JButton STUDENT_BUTTON;
    private javax.swing.JButton STUD_BUTTON;
    private javax.swing.JLabel WELCOME;
    private javax.swing.JLabel Welcome;
    private javax.swing.JButton cancel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelwelcome;
    // End of variables declaration//GEN-END:variables
}
