/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quiz;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Div
 */
public class Lecturer extends javax.swing.JFrame {
private DBConnection db = new DBConnection();
    /**
     * Creates new form LECTURER
     */
    public Lecturer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLecturer = new javax.swing.JPanel();
        Lecturer = new javax.swing.JLabel();
        login_id = new javax.swing.JTextField();
        lect_name = new javax.swing.JTextField();
        Password1 = new javax.swing.JPasswordField();
        loginid = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        password1 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelLecturer.setBackground(new java.awt.Color(255, 255, 102));
        jPanelLecturer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lecturer.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        Lecturer.setText("LECTURER");
        jPanelLecturer.add(Lecturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 11, -1, -1));
        jPanelLecturer.add(login_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 91, -1));

        lect_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lect_nameActionPerformed(evt);
            }
        });
        jPanelLecturer.add(lect_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 91, -1));

        Password1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password1ActionPerformed(evt);
            }
        });
        jPanelLecturer.add(Password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 91, -1));

        loginid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loginid.setText("Login_id :");
        jPanelLecturer.add(loginid, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 76, -1));

        name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name.setText("Name :");
        jPanelLecturer.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 76, -1));

        password1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        password1.setText("Password :");
        jPanelLecturer.add(password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanelLecturer.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compressed_1644044182681.jpeg"))); // NOI18N
        jPanelLecturer.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLecturer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLecturer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lect_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lect_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lect_nameActionPerformed

    private void Password1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password1ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
         ResultSet s;
        
    
        String Login=login_id.getText();
        String pass=new String(Password1.getPassword());
        String Name=lect_name.getText();
        try{
            
            String sql=("select * from lecturer where login_id='"+Login+"' and password='"+pass+"' and name='"+Name+"'");
            PreparedStatement p = db.getConnection().prepareStatement(sql);
        s=p.executeQuery(sql);
        
        if(s.next())
        {
            System.out.println("login successful");
            JOptionPane.showMessageDialog(null,"Successful login");
                setVisible(false);
                 new Subject(Login).setVisible(true);
                
        }
        else{
            System.out.println("Login Failed");
              JOptionPane.showMessageDialog(null,"Login Failed");
        }
       db.close();
        
         
        }
         catch (SQLException ex) {
               java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
               System.out.println("Login Failed");
              JOptionPane.showMessageDialog(null,"Login Failed");
           }
            
            
        
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lecturer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lecturer;
    private javax.swing.JPasswordField Password1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelLecturer;
    private javax.swing.JTextField lect_name;
    private javax.swing.JTextField login_id;
    private javax.swing.JLabel loginid;
    private javax.swing.JLabel name;
    private javax.swing.JLabel password1;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
